# Lazygit Configuration
# Terminal UI for git commands

gui:
  # Theme
  theme:
    activeBorderColor:
      - '#7aa2f7'
      - bold
    inactiveBorderColor:
      - '#545c7e'
    optionsTextColor:
      - '#7aa2f7'
    selectedLineBgColor:
      - '#283457'
    selectedRangeBgColor:
      - '#283457'
    cherryPickedCommitBgColor:
      - '#bb9af7'
    cherryPickedCommitFgColor:
      - '#1a1b26'
    unstagedChangesColor:
      - red
    defaultFgColor:
      - '#c0caf5'
    searchingActiveBorderColor:
      - '#e0af68'
      - bold

  # Layout
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showBranchLogGraph: true
  showBottomLine: true
  showCommandLog: true
  showIcons: true
  
  # UI behavior
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: 'flexible'
  
  # Time format
  timeFormat: '02 Jan 06 15:04 MST'
  
  # Command log
  commandLogSize: 8
  splitDiff: 'auto'

# Git behavior
git:
  # Paging
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  
  # Commits
  commit:
    signOff: false
    verbose: default
  
  # Merging
  merging:
    manualCommit: false
    args: ''
  
  # Pull
  pull:
    mode: 'auto'
  
  # Skip hook prefix
  skipHookPrefix: WIP
  
  # Auto-fetch
  autoFetch: true
  autoRefresh: true
  
  # Branch log
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --'
  
  # All branches log
  allBranchesLogCmd: 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --all'
  
  # Override git config
  overrideGpg: false
  
  # Disable force pushing
  disableForcePushing: false
  
  # Parse emoji
  parseEmoji: true

# Update behavior
update:
  method: prompt
  days: 14

# Refresher
refresher:
  refreshInterval: 10
  fetchInterval: 60

# Reporting
reporting: 'undetermined'

# Splash screen
splashUpdatesIndex: 0

# Confirmation on quit
confirmOnQuit: false

# Quit on top level return
quitOnTopLevelReturn: false

# OS specific
os:
  # Edit command
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} {{filename}}'
  
  # Open command
  openCommand: 'open {{filename}}'

# Disable startup popup
disableStartupPopups: false

# Custom commands
customCommands:
  - key: '<c-r>'
    command: 'git rebase -i {{.SelectedCommit.Sha}}^'
    context: 'commits'
    description: 'Interactive rebase from selected commit'
    
  - key: 'C'
    command: 'git commit --amend --no-edit'
    context: 'files'
    description: 'Amend commit without editing message'
    
  - key: 'P'
    command: 'git push --force-with-lease'
    context: 'commits'
    description: 'Force push with lease'
    
  - key: 'Z'
    command: 'git stash pop'
    context: 'stash'
    description: 'Pop stash'

# Keybindings
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    scrollLeft: 'H'
    scrollRight: 'L'
    gotoTop: '<'
    gotoBottom: '>'
    toggleRangeSelect: 'v'
    rangeSelectDown: '<s-down>'
    rangeSelectUp: '<s-up>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextBlock-alt2: '<tab>'
    prevBlock-alt2: '<backtab>'
    jumpToBlock: '1'
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: '/'
    optionMenu: 'x'
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirmInEditor: '<a-enter>'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeCustomCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<c-p>'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<c-z>'
    filteringMenu: '<c-s>'
    diffingMenu: 'W'
    diffingMenu-alt: '<c-e>'
    copyToClipboard: '<c-o>'
    openRecentRepos: '<c-r>'
    submitEditorText: '<enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
    
  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'
    allBranchesLogGraph: 'a'
    
  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    findBaseCommitForFixup: '<c-f>'
    confirmDiscard: 'x'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
    openMergeTool: 'M'
    openStatusFilter: '<c-b>'
    
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    copyPullRequestURL: '<c-y>'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    renameBranch: 'R'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    createTag: 'T'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'
    
  worktrees:
    viewWorktreeOptions: 'w'
    
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    amendToCommit: 'A'
    resetCommitAuthor: 'a'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: 'C'
    pasteCommits: 'V'
    markCommitAsBaseForRebase: 'B'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitAttributeToClipboard: 'y'
    openLogMenu: '<c-l>'
    openInBrowser: 'o'
    viewBisectOptions: 'b'
    startInteractiveRebase: 'i'
    
  amendAttribute:
    resetAuthor: 'a'
    setAuthor: 'A'
    addCoAuthor: 'c'
    
  stash:
    popStash: 'g'
    renameStash: 'r'
    
  commitFiles:
    checkoutCommitFile: 'c'
    
  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
    editSelectHunk: 'E'
    
  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'
    
  commitMessage:
    switchToEditor: '<c-o>'
