# Alacritty Configuration
# GPU-accelerated terminal emulator

# Import additional configuration files
import:
  - ~/.config/alacritty/themes/tokyonight.yml

# Environment variables
env:
  TERM: xterm-256color

# Window configuration
window:
  # Window dimensions (changes require restart)
  dimensions:
    columns: 120
    lines: 40

  # Window padding (blank space around terminal content)
  padding:
    x: 10
    y: 10

  # Spread additional padding evenly around the terminal content
  dynamic_padding: true

  # Window decorations
  decorations: buttonless

  # Opacity
  opacity: 0.95

  # Startup mode
  startup_mode: Windowed

  # Window title
  title: Alacritty
  dynamic_title: true

  # Window class (Linux/BSD only)
  class:
    instance: Alacritty
    general: Alacritty

  # Decorations theme variant
  decorations_theme_variant: None

# Scrolling
scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  # Normal font face
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular

  # Bold font face
  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold

  # Italic font face
  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic

  # Bold italic font face
  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: Bold Italic

  # Font size
  size: 14.0

  # Offset
  offset:
    x: 0
    y: 0

  # Glyph offset
  glyph_offset:
    x: 0
    y: 0

  # Use built-in font for box drawing characters
  builtin_box_drawing: true

# Colors (Tokyo Night theme)
colors:
  primary:
    background: '#1a1b26'
    foreground: '#c0caf5'

  normal:
    black:   '#15161e'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#a9b1d6'

  bright:
    black:   '#414868'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#c0caf5'

  selection:
    background: '#364a82'
    foreground: '#c0caf5'

  indexed_colors:
    - { index: 16, color: '#ff9e64' }
    - { index: 17, color: '#db4b4b' }

# Bell
bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

# Selection
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

# Cursor
cursor:
  style:
    shape: Block
    blinking: Off
  
  vi_mode_style: None
  unfocused_hollow: true
  thickness: 0.15

# Live config reload
live_config_reload: true

# Shell
shell:
  program: /bin/zsh
  args:
    - --login

# Mouse
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

# Hints
hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: U
        mods: Control|Shift

# Key bindings
key_bindings:
  # Common macOS bindings
  - { key: Plus,     mods: Command,       action: IncreaseFontSize }
  - { key: Minus,    mods: Command,       action: DecreaseFontSize }
  - { key: Key0,     mods: Command,       action: ResetFontSize    }
  - { key: K,        mods: Command,       action: ClearHistory     }
  - { key: V,        mods: Command,       action: Paste            }
  - { key: C,        mods: Command,       action: Copy             }
  - { key: Q,        mods: Command,       action: Quit             }
  - { key: W,        mods: Command,       action: Quit             }
  - { key: N,        mods: Command,       action: SpawnNewInstance }
  
  # Vim mode
  - { key: Space,    mods: Shift|Control, mode: ~Search,    action: ToggleViMode     }
  
  # Search mode
  - { key: F,        mods: Command,       mode: ~Search,    action: SearchForward    }
  - { key: B,        mods: Command,       mode: ~Search,    action: SearchBackward   }
  
  # Fullscreen
  - { key: Return,   mods: Command,       action: ToggleFullscreen }
  
  # Clear screen and scrollback
  - { key: L,        mods: Control,       action: ClearLogNotice   }
  
  # Hide/Show Alacritty
  - { key: H,        mods: Command,       action: Hide             }
  - { key: M,        mods: Command,       action: Minimize         }
